config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get 'binance_pairs', to: 'binance_pairs#index', as: 'binance_pairs_index'
  post 'binance_pairs/add_to_favorites', to: 'binance_pairs#add_to_favorites', as: 'add_to_favorites'


  resources :coins, only: [:index]
  resources :favorites, only: [:index, :destroy]
  get 'profile', to: 'profile#index', as: 'profile'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/binance_pairs_controller.rb
class BinancePairsController < ApplicationController
  require 'httparty'

  def index
    @pairs = fetch_binance_pairs
    @pairs_count = @pairs.count
  end

  def add_to_favorites
    symbol = params[:symbol]
    Favorite.create(symbol: symbol)
    redirect_to binance_pairs_index_path, notice: 'Pair added to favorites'
  end

  private

  def fetch_binance_pairs
    response = HTTParty.get('https://api.binance.com/api/v3/ticker/price')
    pairs = response.parsed_response.select { |pair| pair['symbol'].end_with?('BTC') }
    pairs.map { |pair| { symbol: pair['symbol'] } }
  end
end

app/controllers/coins_controller.rb
# class CoinsController < ApplicationController
#   def index
#     service = BinanceService.new
#     @tickers = service.fetch_tickers.parsed_response

#     # Фільтрація ліквідних монет
#     @tickers = @tickers.select do |ticker|
#       ticker['quoteVolume'].to_f > 100_000 && ticker['priceChangePercent'].to_f.abs < 10
#     end
#     @tickers = @tickers.sort_by { |ticker| -ticker['quoteVolume'].to_f }

#     # Загальна кількість валютних пар
#     @total_pairs = @tickers.size
#   end
# end


class CoinsController < ApplicationController
  def index
    service = BinanceService.new
    @tickers = service.fetch_tickers.parsed_response

    # Фільтрація ліквідних монет
    @tickers = @tickers.select do |ticker|
      ticker['quoteVolume'].to_f > 100_000 && ticker['priceChangePercent'].to_f.abs < 10
    end
    @tickers = @tickers.sort_by { |ticker| -ticker['quoteVolume'].to_f }

    # Якщо є параметр пошуку, фільтруємо валютні пари за символом
    if params[:search].present?
      search_query = params[:search].to_s.upcase
      @tickers = @tickers.select do |ticker|
        ticker['symbol'].upcase.include?(search_query)
      end
    end

    # Загальна кількість валютних пар
    @total_pairs = @tickers.size
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end

  def destroy
    favorite = Favorite.find(params[:id])
    favorite.destroy
    redirect_to favorites_path, notice: 'Pair removed from favorites'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  require 'httparty'
  require 'dotenv/load'
  require 'json'

  def index
    @account_info = fetch_account_info
    @total_usdt = calculate_total_usdt(@account_info)
    @balances_with_usdt = calculate_balances_with_usdt(@account_info)
  end

  private

  def fetch_account_info
    api_key = ENV['BINANCE_API_KEY']
    api_secret = ENV['BINANCE_API_SECRET']
    timestamp = Time.now.to_i * 1000
    params = {
      timestamp: timestamp
    }
    signature = OpenSSL::HMAC.hexdigest('SHA256', api_secret, params.to_query)
    headers = {
      'X-MBX-APIKEY' => api_key
    }
    response = HTTParty.get("https://api.binance.com/api/v3/account?#{params.to_query}&signature=#{signature}", headers: headers)
    response.parsed_response
  end

  def calculate_total_usdt(account_info)
    total_usdt = 0.0
    account_info['balances'].each do |balance|
      if balance['free'].to_f > 0
        price_in_usdt = fetch_price_in_usdt(balance['asset'])
        total_usdt += balance['free'].to_f * price_in_usdt
      end
    end
    total_usdt
  end

  def calculate_balances_with_usdt(account_info)
    account_info['balances'].map do |balance|
      if balance['free'].to_f > 0
        price_in_usdt = fetch_price_in_usdt(balance['asset'])
        balance.merge('usdt_value' => balance['free'].to_f * price_in_usdt)
      else
        balance
      end
    end
  end

  def fetch_price_in_usdt(asset)
    response = HTTParty.get("https://api.binance.com/api/v3/ticker/price?symbol=#{asset}USDT")
    response.parsed_response['price'].to_f
  rescue
    0.0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/binance_pairs_helper.rb
module BinancePairsHelper
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/binance_pairs/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4 text-center">Binance Trading Pairs for BTC (<%= @pairs_count %> available)</h1>
  <%= link_to 'Go to Favorites', favorites_path, class: 'btn btn-sm btn-primary mb-3' %>

  <div class="table-responsive">
    <table class="table table-bordered table-hover custom-table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
          <th>#</th>
          <th>Symbol</th>
        </tr>
      </thead>
      <tbody>
        <% @pairs.each_slice(8).with_index do |slice, index| %>
          <tr>
            <% slice.each_with_index do |pair, pair_index| %>
              <td><%= index * 8 + pair_index + 1 %></td>
              <td>
                <div class="d-flex flex-column align-items-start">
                  <%= link_to pair[:symbol].gsub('BTC', '/BTC'), "https://www.binance.com/en/trade/#{pair[:symbol]}", target: '_blank', class: 'text-primary custom-link' %>
                  <%= button_to 'Add', add_to_favorites_path(symbol: pair[:symbol]), method: :post, class: 'btn btn-sm btn-success mt-1 custom-button' %>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<style>
/* Загальний стиль для таблиці */
.custom-table {
  border-collapse: collapse;
  width: 100%;
  margin-top: 20px;
}

.custom-table th, .custom-table td {
  text-align: center;
  padding: 12px;
  vertical-align: middle;
}

.custom-table th {
  background-color: #343a40;
  color: #ffffff;
  font-weight: bold;
}

.custom-table td {
  background-color: #f8f9fa;
}

.custom-table tbody tr:nth-child(odd) {
  background-color: #f1f1f1;
}

.custom-table tbody tr:hover {
  background-color: #e2e6ea;
  cursor: pointer;
}

/* Стиль для лінків */
.custom-link {
  font-size: 14px;
  text-decoration: none;
  color: #007bff;
  transition: color 0.3s ease;
}

.custom-link:hover {
  color: #0056b3;
  text-decoration: underline;
}

/* Стиль для кнопок "Add" */
.custom-button {
  font-size: 12px;
  background-color: #28a745;
  border: none;
  transition: background-color 0.3s ease;
}

.custom-button:hover {
  background-color: #218838;
  cursor: pointer;
}

/* Стиль для кнопки "Go to Favorites" */
.btn-primary {
  background-color: #007bff;
  border-color: #007bff;
}

.btn-primary:hover {
  background-color: #0056b3;
  border-color: #004085;
}

/* Адаптивність для малих екранів */
@media (max-width: 767px) {
  .custom-table th, .custom-table td {
    font-size: 12px;
    padding: 8px;
  }

  .btn-sm {
    font-size: 10px;
  }
}
</style>

app/views/coins/index.html.erb
<div class="container my-5">
  <h1 class="text-center mb-4">Список ліквідних монет (Доступно пар: <%= @total_pairs %>)</h1>

  <!-- Пошукове поле -->
  <div class="mb-3">
    <%= form_with(url: coins_path, method: :get, local: true) do %>
      <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Пошук валютної пари..." %>
      <%= submit_tag "Пошук", class: 'btn btn-primary mt-2' %>
    <% end %>
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover align-middle" id="currenciesTable">
      <thead class="table-dark">
        <tr>
          <th scope="col" class="text-center">#</th>
          <th scope="col">Назва</th>
          <th scope="col">Валютна пара</th>
          <th scope="col">Обсяг торгів (24 год)</th>
          <th scope="col">Зміна ціни (%)</th>
        </tr>
      </thead>
      <tbody>
        <% @tickers.each_with_index do |ticker, index| %>
          <% base_currency, quote_currency = ticker['symbol'][0..-5], ticker['symbol'][-4..] %>
          <tr>
            <td class="text-center"><%= index + 1 %></td>
            <td>
              <%= link_to "#{base_currency}/#{quote_currency}", 
                          "https://www.binance.com/en/trade/#{base_currency}_#{quote_currency}",
                          target: '_blank', rel: 'noopener', class: 'text-decoration-none' %>
            </td>
            <td><%= "#{base_currency}/#{quote_currency}" %></td>
            <td><%= number_with_delimiter(ticker['quoteVolume'].to_f, delimiter: ',') %></td>
            <td class="<%= ticker['priceChangePercent'].to_f.positive? ? 'text-success' : 'text-danger' %>">
              <%= ticker['priceChangePercent'].to_f %> %
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="container mt-5">
  <h1 class="mb-4 text-center">Favorite Trading Pairs</h1>
  <%= link_to 'Back to Pairs', binance_pairs_index_path, class: 'btn btn-sm btn-secondary mb-3 custom-back-btn' %>
  
  <div class="table-responsive">
    <table class="table table-bordered table-hover custom-table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Symbol</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @favorites.each_with_index do |favorite, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td>
              <%= link_to favorite.symbol.gsub('BTC', '/BTC'), "https://www.binance.com/en/trade/#{favorite.symbol}", target: '_blank', class: 'text-primary custom-link' %>
            </td>
            <td>
              <%= button_to 'Remove', favorite_path(favorite), method: :delete, class: 'btn btn-sm btn-danger custom-remove-btn', data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<style>
/* Загальний стиль для таблиці */
.custom-table {
  border-collapse: collapse;
  width: 100%;
  margin-top: 20px;
}

.custom-table th, .custom-table td {
  text-align: center;
  padding: 12px;
  vertical-align: middle;
}

.custom-table th {
  background-color: #343a40;
  color: #ffffff;
  font-weight: bold;
}

.custom-table td {
  background-color: #f8f9fa;
}

.custom-table tbody tr:nth-child(odd) {
  background-color: #f1f1f1;
}

.custom-table tbody tr:hover {
  background-color: #e2e6ea;
  cursor: pointer;
}

/* Стиль для лінків */
.custom-link {
  font-size: 14px;
  text-decoration: none;
  color: #007bff;
  transition: color 0.3s ease;
}

.custom-link:hover {
  color: #0056b3;
  text-decoration: underline;
}

/* Стиль для кнопки "Remove" */
.custom-remove-btn {
  font-size: 12px;
  background-color: #dc3545;
  border: none;
  transition: background-color 0.3s ease;
}

.custom-remove-btn:hover {
  background-color: #c82333;
  cursor: pointer;
}

/* Стиль для кнопки "Back to Pairs" */
.custom-back-btn {
  background-color: #6c757d;
  border-color: #6c757d;
}

.custom-back-btn:hover {
  background-color: #5a6268;
  border-color: #4e555b;
}

/* Адаптивність для малих екранів */
@media (max-width: 767px) {
  .custom-table th, .custom-table td {
    font-size: 12px;
    padding: 8px;
  }

  .btn-sm {
    font-size: 10px;
  }
}
</style>

app/views/home/index.html.erb
<h1 class="text-center mb-4">Блог</h1>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img src="<%= asset_path('ruby_yelow_2.png') %>" alt="Logo" height="40">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Coin pairs', binance_pairs_index_path, class: 'nav-link active', aria: { current: 'page' } %>
          </li>
          <li class="nav-item">
            <%= link_to 'Liquid', coins_path, class: 'nav-link active', aria: { current: 'page' } %>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Event</a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Profile', profile_path, class: 'nav-link active', aria: { current: 'page' } %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Helper Bot" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

  </body>
</html>